P = [ 'Adams','Arthur','B Harrison','Buchanan','Bush','Carter','Cleveland','Clinton',
      'Coolidge','Eisenhower','FD Roosevelt','Fillmore','Ford','Grant','GW Bush',
      'Hayes','Hoover','Jackson','Jefferson','Johnson','JG Adams','Kennedy','LB Johnson',
      'Lincoln','Madison','McKinley','Monroe','Nixon','Obama','Pierce','Polk','Reagan',
      'Roosevelt','Taft','Taylor','Truman','Tyler','Van Buren','Washington','Wilson' ]

F = [ 'adams0.txt','adams1.txt','adams2.txt','adams3.txt',
      'arthur0.txt','arthur1.txt','arthur2.txt','arthur3.txt',
      'bharrison0.txt','bharrison1.txt','bharrison2.txt','bharrison3.txt',
      'buchanan0.txt','buchanan1.txt','buchanan2.txt','buchanan3.txt',
      'bush0.txt','bush1.txt','bush2.txt','bush3.txt',
      'carter0.txt','carter1.txt','carter2.txt','carter3.txt',
      'cleveland0.txt','cleveland1.txt','cleveland2.txt','cleveland3.txt',
      'clinton0.txt','clinton1.txt','clinton2.txt','clinton3.txt',
      'coolidge0.txt','coolidge1.txt','coolidge2.txt','coolidge3.txt',
      'eisenhower0.txt','eisenhower1.txt','eisenhower2.txt','eisenhower3.txt',
      'fdroosevelt0.txt','fdroosevelt1.txt','fdroosevelt2.txt','fdroosevelt3.txt',
      'fillmore0.txt','fillmore1.txt','fillmore2.txt','fillmore3.txt',
      'ford0.txt','ford1.txt','ford2.txt','ford3.txt',
      'grant0.txt','grant1.txt','grant2.txt','grant3.txt',
      'gwbush0.txt','gwbush1.txt','gwbush2.txt','gwbush3.txt',
      'hayes0.txt','hayes1.txt','hayes2.txt','hayes3.txt',
      'hoover0.txt','hoover1.txt','hoover2.txt','hoover3.txt',
      'jackson0.txt','jackson1.txt','jackson2.txt','jackson3.txt',
      'jefferson0.txt','jefferson1.txt','jefferson2.txt','jefferson3.txt',
      'johnson0.txt','johnson1.txt','johnson2.txt','johnson3.txt',
      'jqadams0.txt','jqadams1.txt','jqadams2.txt','jqadams3.txt',
      'kennedy0.txt','kennedy1.txt','kennedy2.txt','kennedy3.txt',
      'lbjohnson0.txt','lbjohnson1.txt','lbjohnson2.txt','lbjohnson3.txt',
      'lincoln0.txt','lincoln1.txt','lincoln2.txt','lincoln3.txt',
      'madison0.txt','madison1.txt','madison2.txt','madison3.txt',
      'mckinley0.txt','mckinley1.txt','mckinley2.txt','mckinley3.txt',
      'monroe0.txt','monroe1.txt','monroe2.txt','monroe3.txt',
      'nixon0.txt','nixon1.txt','nixon2.txt','nixon3.txt',
      'obama0.txt','obama1.txt','obama2.txt','obama3.txt',
      'pierce0.txt','pierce1.txt','pierce2.txt','pierce3.txt',
      'polk0.txt','polk1.txt','polk2.txt','polk3.txt',
      'reagan0.txt','reagan1.txt','reagan2.txt','reagan3.txt',
      'roosevelt0.txt','roosevelt1.txt','roosevelt2.txt','roosevelt3.txt',
      'taft0.txt','taft1.txt','taft2.txt','taft3.txt',
      'taylor0.txt','taylor1.txt','taylor2.txt','taylor3.txt',
      'truman0.txt','truman1.txt','truman2.txt','truman3.txt',
      'tyler0.txt','tyler1.txt','tyler2.txt','tyler3.txt',
      'vanburen0.txt','vanburen1.txt','vanburen2.txt','vanburen3.txt',
      'washington0.txt','washington1.txt','washington2.txt','washington3.txt',
      'wilson0.txt','wilson1.txt','wilson2.txt','wilson3.txt' ]

U = [ 'Unknown0.txt','Unknown1.txt','Unknown2.txt','Unknown3.txt','Unknown4.txt' ]
